apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  my.cnf: |-
    [client]
    default-character-set=utf8mb4
    [mysql]
    default-character-set=utf8mb4
    [mysqld] 
    max_connections=2000
    slow_query_log=0
    slow_query_log=ON
    long_query_time=10
    log_queries_not_using_indexes=ON
    slow_query_log-file=/var/log/mysql/mysql-slow.sql
    secure_file_priv=/var/lib/mysql
